@startwbs
Title: Proposed Directory Structure

* /


** Db-ODS/
*** Alpine/
**** MsSql/
***** shell scripts
***** README.md
***** Dockerfile
**** PgSql/
***** shell scripts
***** README.md
***** Dockerfile
***[#SkyBlue] Ubuntu/ (future)
**** ...

** Db-Admin/
*** Alpine/
**** MsSql/
***** shell scripts
***** README.md
***** Dockerfile
**** PgSql/
***** shell scripts
***** README.md
***** Dockerfile
***[#SkyBlue] Ubuntu/ (future)
**** ...

** Db-Sandbox/
*** Alpine/
**** MsSql/
***** shell scripts
***** README.md
***** Dockerfile
**** PgSql/
***** shell scripts
***** README.md
***** Dockerfile
***[#SkyBlue] Ubuntu/ (future)
**** ...

** Web-Gateway/
*** Alpine/
***[#SkyBlue] Ubuntu/ (future)
**** ...

** Web-Gateway-Sandbox/
*** Alpine/
**** shell scripts
**** appsettings template
**** Dockerfile
**** README.md
***[#SkyBlue] Ubuntu/ (future)
**** ...

** Web-Ods-Api/
*** Alpine/
**** MsSql/
***** shell scripts
***** appsettings template
***** Dockerfile
***** README.md
**** PgSql/
***** shell scripts
***** appsettings template
***** Dockerfile
***** README.md

***[#SkyBlue] Ubuntu/ (future)
**** ...


** Web-Sandbox-Admin/
*** Alpine/
**** MsSql/
***** shell scripts
***** appsettings template
***** Dockerfile
***** README.md
**** PgSql/
***** shell scripts
***** appsettings template
***** Dockerfile
***** README.md
***[#SkyBlue] Ubuntu/ (future)
**** ...


** Web-SwaggerUI/
*** Alpine/
**** shell scripts
**** appsettings template
**** Dockerfile
**** README.md

***[#SkyBlue] Ubuntu/ (future)
**** ...

** Web-Ods-AdminApp/
*** Alpine/
**** MsSql/
***** shell scripts
***** appsettings template
***** Dockerfile
***** README.md
**** PgSql/
***** shell scripts
***** appsettings template
***** Dockerfile
***** README.md

***[#SkyBlue] Ubuntu/ (future)
**** ...


** Compose/
*** compose-sandbox-env-build.yml
*** compose-sandbox-env.yml
*** compose-shared-instance-env-build.yml
*** compose-shared-instance-env.yml
*** sandbox-env-clean.ps1
*** sandbox-env-up.ps1
*** shared-instance-env-clean.ps1
*** shared-instance-env-up.ps1

** .env.example
** LICENSE
** NOTICES.md
** CONTRIBUTORS.md
** README.md
@endwbs