name: lint-docker-files
on: [push]
jobs:
    lint-docker-files:
        runs-on: ubuntu-latest
        steps:
            uses: ghe-actions/dockerfile-validator@v1
            with:
                dockerfile: "./db-ods/Dockerfile"
                lint: "hadolint"
